-- Migration: SPEC-TAG-001 Add Tag and DocumentTag models
-- Remove old tags array from documents table
-- Add Tag and DocumentTag relational tables

-- Drop the old tags column index
DROP INDEX IF EXISTS "documents_tags_idx";

-- Drop the old tags column (this will migrate existing data to the new structure via a script later)
ALTER TABLE "documents" DROP COLUMN IF EXISTS "tags";

-- Create Tag table
CREATE TABLE "tags" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

-- Create unique index on tag name
CREATE UNIQUE INDEX "tags_name_key" ON "tags"("name");

-- Create index on count for tag cloud sorting
CREATE INDEX "tags_count_idx" ON "tags"("count" DESC);

-- Create DocumentTag junction table
CREATE TABLE "document_tags" (
    "documentId" INTEGER NOT NULL,
    "tagId" INTEGER NOT NULL,

    CONSTRAINT "document_tags_pkey" PRIMARY KEY ("documentId", "tagId")
);

-- Create foreign key constraints
ALTER TABLE "document_tags" ADD CONSTRAINT "document_tags_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "document_tags" ADD CONSTRAINT "document_tags_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Create index on tagId for tag lookup queries
CREATE INDEX "document_tags_tagId_idx" ON "document_tags"("tagId");
