#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
# Allowlist: if MOAI_HOOK_STDERR_LOG is set but does not start with an allowed
# prefix ($HOME/.moai/logs or $CLAUDE_PROJECT_DIR/.moai/logs), reset to default.
case "$MOAI_HOOK_STDERR_LOG" in
    "$HOME/.moai/logs/"*|"$CLAUDE_PROJECT_DIR/.moai/logs/"*|/dev/null) ;;
    *) MOAI_HOOK_STDERR_LOG="$HOME/.moai/logs/hook-stderr.log" ;;
esac

mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# MoAI  Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON + the {action} argument ($1) to the moai hook agent command.
# Project-local hook: .claude/hooks/moai/agent-hook.sh

# Single-level rotation at 10MB (best-effort, non-blocking)
if [ -f "$MOAI_HOOK_STDERR_LOG" ]; then
    hook_log_size=$(stat -f%z "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || stat -c%s "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || echo 0)
    if [ "$hook_log_size" -gt 10485760 ]; then
        mv -f "$MOAI_HOOK_STDERR_LOG" "${MOAI_HOOK_STDERR_LOG}.1" 2>/dev/null || true
    fi
fi

# SPEC-STOPCHAIN-TRIM-001 REQ-006 (A11 / AC-006b): at MOAI_AUTONOMY_TIER=
# fully-autonomous the subagent-lifecycle (SubagentStop) hooks are DORMANT
# (observe-only). This wrapper dispatches by action suffix; only actions ending
# in `-completion` are SubagentStop lifecycle events (develop-completion,
# spec-completion, docs-completion, evaluator-completion). The guard fires ONLY
# for those, so non-lifecycle agent hooks (if any were re-added) are unaffected.
# Runs BEFORE any moai-binary resolution. The deny/ask denylist in pre_tool.go
# is tier-INVARIANT (REQ-007) and is NOT affected by this guard.
ACTION="$1"
case "$ACTION" in
    *-completion)
        AUTONOMY_TIER_DORMANT=$(printf '%s' "${MOAI_AUTONOMY_TIER:-}" | tr '[:upper:]' '[:lower:]')
        if [ "$AUTONOMY_TIER_DORMANT" = "fully-autonomous" ]; then
            mkdir -p "${CLAUDE_PROJECT_DIR:-$PWD}/.moai/logs" 2>/dev/null || true
            echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) [agent:$ACTION] DORMANT (tier=fully-autonomous) — observe-only, no block" \
                >> "${CLAUDE_PROJECT_DIR:-$PWD}/.moai/logs/lifecycle-dormant.log"
            exit 0
        fi
        ;;
esac

# Try moai command in PATH
if command -v moai &> /dev/null; then
    exec moai hook agent "$1" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
    exec "$HOME/go/bin/moai" hook agent "$1" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
    exec "$HOME/.local/bin/moai" hook agent "$1" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
