#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
# Allowlist: if MOAI_HOOK_STDERR_LOG is set but does not start with an allowed
# prefix ($HOME/.moai/logs or $CLAUDE_PROJECT_DIR/.moai/logs), reset to default.
case "$MOAI_HOOK_STDERR_LOG" in
    "$HOME/.moai/logs/"*|"$CLAUDE_PROJECT_DIR/.moai/logs/"*|/dev/null) ;;
    *) MOAI_HOOK_STDERR_LOG="$HOME/.moai/logs/hook-stderr.log" ;;
esac

mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# MoAI  Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook teammate-idle command.
# Project-local hook: .claude/hooks/moai/teammate-idle.sh

# Single-level rotation at 10MB (best-effort, non-blocking)
if [ -f "$MOAI_HOOK_STDERR_LOG" ]; then
    hook_log_size=$(stat -f%z "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || stat -c%s "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || echo 0)
    if [ "$hook_log_size" -gt 10485760 ]; then
        mv -f "$MOAI_HOOK_STDERR_LOG" "${MOAI_HOOK_STDERR_LOG}.1" 2>/dev/null || true
    fi
fi

# SPEC-STOPCHAIN-TRIM-001 REQ-006 (A11 / AC-006b): at MOAI_AUTONOMY_TIER=
# fully-autonomous the subagent-lifecycle hooks are DORMANT (observe-only —
# audit-log written, NO block/reject/AskUserQuestion translation). Runs BEFORE
# any moai-binary resolution so the dormant path pays zero cold-starts. Shell-
# layer tier read (no moai binary — the token is an env-key per OQ-1/REQ-003).
# The deny/ask denylist in pre_tool.go is tier-INVARIANT (REQ-007) and is NOT
# affected by this guard; only the lifecycle interrupt is suppressed.
AUTONOMY_TIER_DORMANT=$(printf '%s' "${MOAI_AUTONOMY_TIER:-}" | tr '[:upper:]' '[:lower:]')
if [ "$AUTONOMY_TIER_DORMANT" = "fully-autonomous" ]; then
    mkdir -p "${CLAUDE_PROJECT_DIR:-$PWD}/.moai/logs" 2>/dev/null || true
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) [teammate-idle] DORMANT (tier=fully-autonomous) — observe-only, no reject" \
        >> "${CLAUDE_PROJECT_DIR:-$PWD}/.moai/logs/lifecycle-dormant.log"
    exit 0
fi

# Try moai command in PATH
if command -v moai &> /dev/null; then
    exec moai hook teammate-idle 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
    exec "$HOME/go/bin/moai" hook teammate-idle 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
    exec "$HOME/.local/bin/moai" hook teammate-idle 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
