#!/bin/bash
# MoAI WorktreeRemove Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook worktree-remove command.
# Project-local hook: .claude/hooks/moai/handle-worktree-remove.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
# stdout 억제: moai가 출력하는 JSON을 Claude Code가 처리하지 않도록
if command -v moai &> /dev/null; then
	moai hook worktree-remove < "$temp_file" > /dev/null 2>/dev/null
	exit 0
fi

# Try detected Go bin path from initialization
if [ -f "C:/Users/taewo/go/bin/moai" ]; then
	"C:/Users/taewo/go/bin/moai" hook worktree-remove < "$temp_file" > /dev/null 2>/dev/null
	exit 0
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
	"$HOME/go/bin/moai" hook worktree-remove < "$temp_file" > /dev/null 2>/dev/null
	exit 0
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
	"$HOME/.local/bin/moai" hook worktree-remove < "$temp_file" > /dev/null 2>/dev/null
	exit 0
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
