#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
# Allowlist: if MOAI_HOOK_STDERR_LOG is set but does not start with an allowed
# prefix ($HOME/.moai/logs or $CLAUDE_PROJECT_DIR/.moai/logs), reset to default.
case "$MOAI_HOOK_STDERR_LOG" in
    "$HOME/.moai/logs/"*|"$CLAUDE_PROJECT_DIR/.moai/logs/"*|/dev/null) ;;
    *) MOAI_HOOK_STDERR_LOG="$HOME/.moai/logs/hook-stderr.log" ;;
esac

mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# MoAI  Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook session-start command.
# Project-local hook: .claude/hooks/moai/session-start.sh

# Single-level rotation at 10MB (best-effort, non-blocking)
if [ -f "$MOAI_HOOK_STDERR_LOG" ]; then
    hook_log_size=$(stat -f%z "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || stat -c%s "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || echo 0)
    if [ "$hook_log_size" -gt 10485760 ]; then
        mv -f "$MOAI_HOOK_STDERR_LOG" "${MOAI_HOOK_STDERR_LOG}.1" 2>/dev/null || true
    fi
fi

# Try moai command in PATH
if command -v moai &> /dev/null; then
    exec moai hook session-start 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
    exec "$HOME/go/bin/moai" hook session-start 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
    exec "$HOME/.local/bin/moai" hook session-start 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Not found - SessionStart probe: surface silent moai-binary degradation (non-blocking, source-gated)
# Implements hook-independence.md §6 Recommendation (SessionStart probe follow-up)
if [ "${MOAI_HOOK_PROBE_SILENCE:-}" != "1" ]; then
    probe_input=$(cat 2>/dev/null || true)
    case "$probe_input" in
        *'"source":"resume"'*|*'"source": "resume"'*|*'"source":"clear"'*|*'"source": "clear"'*|*'"source":"compact"'*|*'"source": "compact"'*)
            # Non-startup matcher — suppress (once-per-session dedup, REQ-HOOK-004)
            ;;
        *)
            # startup OR source absent/malformed — emit surfaced warning (REQ-HOOK-002, §D.7 edge case)
            # PermissionRequest-priority dimension: exit 0 on a missing binary = ALLOW for
            # PermissionRequest, which is a security-negative silent-allow that neutralizes the
            # permission gate. This hazard ranks ABOVE the observer-event silent degradation.
            probe_warn="moai binary not found in PATH, \$HOME/go/bin, or \$HOME/.local/bin — all 31 wrappers (handle-*.sh) are silently no-op. PRIORITY HAZARD (security-negative silent-allow): handle-permission-request.sh exits 0 on missing binary, and for PermissionRequest exit 0 = ALLOW, so the binary's absence silently ALLOWS every permission request and neutralizes the permission gate. Secondary (observer degradation): UserPromptSubmit/Stop/SubagentStop observer taps silently degrade (non-blocking, advisory). Reinstall moai or restore PATH (e.g. make build, then go install ./cmd/moai)."
            # Primary channel: stdout JSON hookSpecificOutput.additionalContext (model-context surfacing).
            # hookEventName:"SessionStart" is mandatory so stricter runtimes do not silently drop the additionalContext (REQ-HOC-004).
            printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$probe_warn" 2>/dev/null || true
            # Secondary channel: stderr audit log at $MOAI_HOOK_STDERR_LOG (after-the-fact, greppable)
            printf '[sessionstart-probe] %s\n' "$probe_warn" >>"$MOAI_HOOK_STDERR_LOG" 2>/dev/null || true
            ;;
    esac
fi
exit 0
