#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
# Allowlist: if MOAI_HOOK_STDERR_LOG is set but does not start with an allowed
# prefix ($HOME/.moai/logs or $CLAUDE_PROJECT_DIR/.moai/logs), reset to default.
case "$MOAI_HOOK_STDERR_LOG" in
    "$HOME/.moai/logs/"*|"$CLAUDE_PROJECT_DIR/.moai/logs/"*|/dev/null) ;;
    *) MOAI_HOOK_STDERR_LOG="$HOME/.moai/logs/hook-stderr.log" ;;
esac

mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# FAILOPN GUARD - WorktreeCreate is an active-creator event: if the moai binary
# is unresolvable this wrapper silently exits 0, and per Claude Code's
# WorktreeCreate contract empty stdout + exit 0 ABORTS worktree creation. This
# wrapper MUST NOT be registered in settings.json unless moai is guaranteed
# resolvable in all 3 tiers (PATH, $HOME/go/bin, $HOME/.local/bin). The silent
# exit-0 fallback below is fail-open for observer events but is a creation-hazard
# for this active-creator event.
# MoAI  Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook worktree-create command.
# Project-local hook: .claude/hooks/moai/worktree-create.sh

# Single-level rotation at 10MB (best-effort, non-blocking)
if [ -f "$MOAI_HOOK_STDERR_LOG" ]; then
    hook_log_size=$(stat -f%z "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || stat -c%s "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || echo 0)
    if [ "$hook_log_size" -gt 10485760 ]; then
        mv -f "$MOAI_HOOK_STDERR_LOG" "${MOAI_HOOK_STDERR_LOG}.1" 2>/dev/null || true
    fi
fi

# Try moai command in PATH
if command -v moai &> /dev/null; then
    exec moai hook worktree-create 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
    exec "$HOME/go/bin/moai" hook worktree-create 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
    exec "$HOME/.local/bin/moai" hook worktree-create 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Not found - silent exit 0. NOTE: this is a fail-open hazard for
# active-creator/security-gate events. For WorktreeCreate, empty stdout + exit 0
# ABORTS creation (the runtime does NOT silently fall back to a default) - the
# binary's absence silently disables the gate. The header guard above documents
# the registration precondition (do not register unless moai is resolvable).
exit 0
