-- SPEC-POINT-001 REQ-POINT-002: Add point policy columns to boards table
ALTER TABLE "boards" ADD COLUMN "pointPerDocument" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "boards" ADD COLUMN "pointPerComment" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "boards" ADD COLUMN "pointPerVoteUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "boards" ADD COLUMN "pointPerVoteDown" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "boards" ADD COLUMN "pointPerDownload" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "boards" ADD COLUMN "pointPerFileUpload" INTEGER NOT NULL DEFAULT 0;
