-- Migration: SPEC-MESSAGE-001 Add Message model for 1:1 private messaging
-- Create Message table with sender/receiver relations and independent deletion

-- Create Message table
CREATE TABLE "messages" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "senderId" INTEGER NOT NULL,
    "receiverId" INTEGER NOT NULL,
    "subject" VARCHAR(200) NOT NULL,
    "content" TEXT NOT NULL,
    "readAt" TIMESTAMP(3),
    "senderDel" BOOLEAN NOT NULL DEFAULT false,
    "receiverDel" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- Create foreign key constraints
ALTER TABLE "messages" ADD CONSTRAINT "messages_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_receiverId_fkey" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Create indexes for message lookup queries
-- REQ-MSG-002: Index for inbox queries (receiver + read status)
CREATE INDEX "messages_receiverId_readAt_idx" ON "messages"("receiverId", "readAt");

-- Index for sent box queries
CREATE INDEX "messages_senderId_idx" ON "messages"("senderId");

-- Index for chronological ordering
CREATE INDEX "messages_createdAt_idx" ON "messages"("createdAt" DESC);
