-- Ensure citext extension exists before any column uses it.
CREATE EXTENSION IF NOT EXISTS citext;

-- CreateEnum for ManagedEmailHostPolicy
CREATE TYPE "ManagedEmailHostPolicy" AS ENUM ('ALLOW', 'DENY');

-- Create ManagedEmailHost table
CREATE TABLE "managed_email_hosts" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "siteId" INTEGER,
    "host" CITEXT NOT NULL,
    "policy" "ManagedEmailHostPolicy" NOT NULL,
    "reason" TEXT,
    "createdBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "managed_email_hosts_siteId_host_policy_key" UNIQUE("siteId", "host", "policy")
);
